name: webpack-react

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }

      - name: Install dependencies
        run: npm install

      - name: Linting application
        run: npx lint-staged

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }

      - name: Install dependencies
        run: npm install

      - name: Building
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build, lint]
    if: github.ref === 'refs/headers/master'

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }

      - name: Install dependencies
        run: npm install

      - name: Building
        run: npm run build

      - name: Deploying
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build




